[2024-07-22T09:07:46.199+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T09:07:28.098167+00:00 [queued]>
[2024-07-22T09:07:46.215+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T09:07:28.098167+00:00 [queued]>
[2024-07-22T09:07:46.215+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-22T09:07:46.239+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-22 09:07:28.098167+00:00
[2024-07-22T09:07:46.251+0000] {standard_task_runner.py:60} INFO - Started process 10783 to run task
[2024-07-22T09:07:46.268+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fact_order', 'transform_and_load_task', 'manual__2024-07-22T09:07:28.098167+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/fact_order.py', '--cfg-path', '/tmp/tmps2e4ax1n']
[2024-07-22T09:07:46.271+0000] {standard_task_runner.py:88} INFO - Job 237: Subtask transform_and_load_task
[2024-07-22T09:07:46.395+0000] {task_command.py:423} INFO - Running <TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T09:07:28.098167+00:00 [running]> on host 087c584822ad
[2024-07-22T09:07:46.552+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fact_order' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T09:07:28.098167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T09:07:28.098167+00:00'
[2024-07-22T09:07:46.562+0000] {pipeline.py:197} INFO - Missing pipeline option (runner). Executing pipeline using the default runner: DirectRunner.
[2024-07-22T09:07:48.233+0000] {pipeline_options.py:372} WARNING - Discarding unparseable args: ['celery', 'worker']
[2024-07-22T09:07:48.234+0000] {pipeline_options.py:390} WARNING - Discarding invalid overrides: {'save_main_sesion': True}
[2024-07-22T09:07:48.505+0000] {statecache.py:234} INFO - Creating state cache with size 104857600
[2024-07-22T09:08:06.976+0000] {bigquery_file_loads.py:703} INFO - Load job has 1 files. Job name is beam_bq_job_LOAD_factorderbigqueryetl_LOAD_STEP_0a40405e9eaf411e99c5b38b8a85e0b8_5525c64786710cd6cbb950e69cdc9eb4_pane0_partition0.
[2024-07-22T09:08:06.977+0000] {bigquery_file_loads.py:739} INFO - Triggering job beam_bq_job_LOAD_factorderbigqueryetl_LOAD_STEP_0a40405e9eaf411e99c5b38b8a85e0b8_5525c64786710cd6cbb950e69cdc9eb4_pane0_partition0 to load data to BigQuery table <TableReference
 datasetId: 'dw_demo'
 projectId: 'liquid-kite-423215-s2'
 tableId: 'fact_order'>.Schema: {'fields': [{'name': 'ingested_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'last_updated_at', 'type': 'TIMESTAMP', 'mode': 'NULLABLE'}, {'name': 'order_id', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'order_code', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'status', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'customer_id', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'channel', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'currency_code', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'warehouse_code', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'city_shipping_id', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'total_product_order_quantity', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'total_price', 'type': 'NUMERIC', 'mode': 'NULLABLE'}, {'name': 'total_price', 'type': 'NUMERIC', 'mode': 'NULLABLE'}]}. Additional parameters: {}. Source format: NEWLINE_DELIMITED_JSON
[2024-07-22T09:08:07.400+0000] {bigquery_tools.py:594} INFO - Failed to insert job <JobReference
 jobId: 'beam_bq_job_LOAD_factorderbigqueryetl_LOAD_STEP_0a40405e9eaf411e99c5b38b8a85e0b8_5525c64786710cd6cbb950e69cdc9eb4_pane0_partition0'
 projectId: 'liquid-kite-423215-s2'>: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
>
[2024-07-22T09:08:07.405+0000] {bundle_processor.py:237} ERROR - apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
> [while running 'WriteToBigQuery/WriteToBigQuery/BigQueryBatchFileLoads/TriggerLoadJobsWithoutTempTables/ParDo(TriggerLoadJobs)']
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 861, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 997, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line 751, in process
    job_reference = self.bq_wrapper.perform_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 1022, in perform_load_job
    return self._insert_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/utils/retry.py", line 298, in wrapper
    return fun(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 559, in _insert_load_job
    return self._start_job(request, stream=source_stream).jobReference
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 578, in _start_job
    response = self.client.jobs.Insert(request, upload=upload)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py", line 356, in Insert
    return self._RunMethod(
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 731, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 737, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 603, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
>
[2024-07-22T09:08:07.587+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 861, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 997, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line 751, in process
    job_reference = self.bq_wrapper.perform_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 1022, in perform_load_job
    return self._insert_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/utils/retry.py", line 298, in wrapper
    return fun(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 559, in _insert_load_job
    return self._start_job(request, stream=source_stream).jobReference
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 578, in _start_job
    response = self.client.jobs.Insert(request, upload=upload)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py", line 356, in Insert
    return self._RunMethod(
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 731, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 737, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 603, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fact_order.py", line 72, in transform_and_load_task
    (
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 613, in __exit__
    self.result = self.run()
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/pipeline.py", line 587, in run
    return self.runner.run_pipeline(self, self._options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 128, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 204, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 228, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 483, in run_stages
    bundle_results = self._execute_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 811, in _execute_bundle
    self._run_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1048, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1384, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 384, in push
    response = self.worker.do_instruction(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 656, in do_instruction
    return getattr(self, request_type)(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 694, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 1119, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 237, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 569, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 571, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 262, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 265, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 952, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 953, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1437, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1526, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 639, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1621, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1736, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 262, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 265, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 952, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 953, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1437, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1547, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1435, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 861, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 997, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1611, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_file_loads.py", line 751, in process
    job_reference = self.bq_wrapper.perform_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 1022, in perform_load_job
    return self._insert_load_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/utils/retry.py", line 298, in wrapper
    return fun(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 559, in _insert_load_job
    return self._start_job(request, stream=source_stream).jobReference
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/bigquery_tools.py", line 578, in _start_job
    response = self.client.jobs.Insert(request, upload=upload)
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py", line 356, in Insert
    return self._RunMethod(
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 731, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 737, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/airflow/.local/lib/python3.8/site-packages/apitools/base/py/base_api.py", line 603, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
RuntimeError: apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
> [while running 'WriteToBigQuery/WriteToBigQuery/BigQueryBatchFileLoads/TriggerLoadJobsWithoutTempTables/ParDo(TriggerLoadJobs)']
[2024-07-22T09:08:07.627+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fact_order, task_id=transform_and_load_task, execution_date=20240722T090728, start_date=20240722T090746, end_date=20240722T090807
[2024-07-22T09:08:07.642+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 237 for task transform_and_load_task (apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://bigquery.googleapis.com/bigquery/v2/projects/liquid-kite-423215-s2/jobs?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 22 Jul 2024 09:08:07 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '400', 'content-length': '292', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 400,
    "message": "Field total_price already exists in schema",
    "errors": [
      {
        "message": "Field total_price already exists in schema",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
> [while running 'WriteToBigQuery/WriteToBigQuery/BigQueryBatchFileLoads/TriggerLoadJobsWithoutTempTables/ParDo(TriggerLoadJobs)']; 10783)
[2024-07-22T09:08:07.684+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-22T09:08:07.706+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
