[2024-07-16T09:48:16.078+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:48:10.754807+00:00 [queued]>
[2024-07-16T09:48:16.089+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:48:10.754807+00:00 [queued]>
[2024-07-16T09:48:16.090+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-16T09:48:16.109+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-16 09:48:10.754807+00:00
[2024-07-16T09:48:16.117+0000] {standard_task_runner.py:60} INFO - Started process 414 to run task
[2024-07-16T09:48:16.121+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'transform_and_load_task', 'manual__2024-07-16T09:48:10.754807+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmproht8nnw']
[2024-07-16T09:48:16.123+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask transform_and_load_task
[2024-07-16T09:48:16.194+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:48:10.754807+00:00 [running]> on host 3e75606cfc9c
[2024-07-16T09:48:16.308+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T09:48:10.754807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T09:48:10.754807+00:00'
[2024-07-16T09:48:16.318+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 40, in transform_and_load_task
    run_pipeline_beam(avro_file_pattern, table_spec, schema, unique_key)
  File "/opt/airflow/plugins/modules/transformation_load_stage.py", line 99, in run_pipeline
    gcp_options.save_main_session = True
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/options/pipeline_options.py", line 495, in __setattr__
    raise AttributeError(
AttributeError: 'GoogleCloudOptions' object has no attribute 'save_main_session'
[2024-07-16T09:48:16.337+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=transform_and_load_task, execution_date=20240716T094810, start_date=20240716T094816, end_date=20240716T094816
[2024-07-16T09:48:16.352+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task transform_and_load_task ('GoogleCloudOptions' object has no attribute 'save_main_session'; 414)
[2024-07-16T09:48:16.374+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T09:48:16.393+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
