[2024-07-21T11:05:03.618+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-21T11:04:57.393301+00:00 [queued]>
[2024-07-21T11:05:03.631+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-21T11:04:57.393301+00:00 [queued]>
[2024-07-21T11:05:03.632+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-21T11:05:03.650+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data_task> on 2024-07-21 11:04:57.393301+00:00
[2024-07-21T11:05:03.658+0000] {standard_task_runner.py:60} INFO - Started process 2653 to run task
[2024-07-21T11:05:03.663+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'ingest_data_task', 'manual__2024-07-21T11:04:57.393301+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmpzoekkone']
[2024-07-21T11:05:03.665+0000] {standard_task_runner.py:88} INFO - Job 164: Subtask ingest_data_task
[2024-07-21T11:05:03.729+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.ingest_data_task manual__2024-07-21T11:04:57.393301+00:00 [running]> on host 087c584822ad
[2024-07-21T11:05:03.853+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T11:04:57.393301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T11:04:57.393301+00:00'
[2024-07-21T11:05:08.398+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 29, in ingest_data_task
    ingest_data(db_table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 119, in ingest_data
    capture_data_change(pool,table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 90, in capture_data_change
    schema_data_tb = get_schema_avro_file(table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 39, in get_schema_avro_file
    return schema['table_name']
KeyError: 'table_name'
[2024-07-21T11:05:08.434+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=ingest_data_task, execution_date=20240721T110457, start_date=20240721T110503, end_date=20240721T110508
[2024-07-21T11:05:08.460+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 164 for task ingest_data_task ('table_name'; 2653)
[2024-07-21T11:05:08.503+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-21T11:05:08.540+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
