[2024-07-22T09:04:19.266+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fact_order.ingest_data_task manual__2024-07-22T09:04:14.920842+00:00 [queued]>
[2024-07-22T09:04:19.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fact_order.ingest_data_task manual__2024-07-22T09:04:14.920842+00:00 [queued]>
[2024-07-22T09:04:19.278+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-22T09:04:19.293+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data_task> on 2024-07-22 09:04:14.920842+00:00
[2024-07-22T09:04:19.302+0000] {standard_task_runner.py:60} INFO - Started process 10713 to run task
[2024-07-22T09:04:19.307+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fact_order', 'ingest_data_task', 'manual__2024-07-22T09:04:14.920842+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/fact_order.py', '--cfg-path', '/tmp/tmp533vto_4']
[2024-07-22T09:04:19.309+0000] {standard_task_runner.py:88} INFO - Job 234: Subtask ingest_data_task
[2024-07-22T09:04:19.369+0000] {task_command.py:423} INFO - Running <TaskInstance: fact_order.ingest_data_task manual__2024-07-22T09:04:14.920842+00:00 [running]> on host 087c584822ad
[2024-07-22T09:04:19.466+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fact_order' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T09:04:14.920842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T09:04:14.920842+00:00'
[2024-07-22T09:04:19.468+0000] {logging_mixin.py:188} INFO - Start data ingestion stage
[2024-07-22T09:04:24.101+0000] {logging_mixin.py:188} INFO - Number records captured: 8002
[2024-07-22T09:04:24.111+0000] {logging_mixin.py:188} INFO - 3007   2024-06-28 08:04:03
2946   2024-06-28 08:04:03
3468   2024-06-28 08:04:03
7534   2024-06-28 08:04:03
2170   2024-06-28 08:04:03
Name: created_at, dtype: datetime64[ns]
[2024-07-22T09:04:24.131+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fact_order.py", line 29, in ingest_data_task
    ingest_data(db_table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 131, in ingest_data
    capture_data_change(pool,table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 95, in capture_data_change
    capture_data_change_df['last_updated_at'] = capture_data_change_df['created_at'].dt.strftime('%Y-%m-%d %H:%M:%S')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/accessors.py", line 580, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
[2024-07-22T09:04:24.174+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fact_order, task_id=ingest_data_task, execution_date=20240722T090414, start_date=20240722T090419, end_date=20240722T090424
[2024-07-22T09:04:24.198+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 234 for task ingest_data_task (Can only use .dt accessor with datetimelike values; 10713)
[2024-07-22T09:04:24.238+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-22T09:04:24.262+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
