[2024-07-21T10:57:43.395+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-21T10:57:35.980751+00:00 [queued]>
[2024-07-21T10:57:43.414+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-21T10:57:35.980751+00:00 [queued]>
[2024-07-21T10:57:43.415+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-21T10:57:43.434+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data_task> on 2024-07-21 10:57:35.980751+00:00
[2024-07-21T10:57:43.442+0000] {standard_task_runner.py:60} INFO - Started process 2535 to run task
[2024-07-21T10:57:43.447+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'ingest_data_task', 'manual__2024-07-21T10:57:35.980751+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmpxpvhlhj6']
[2024-07-21T10:57:43.450+0000] {standard_task_runner.py:88} INFO - Job 162: Subtask ingest_data_task
[2024-07-21T10:57:43.513+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.ingest_data_task manual__2024-07-21T10:57:35.980751+00:00 [running]> on host 087c584822ad
[2024-07-21T10:57:43.623+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-21T10:57:35.980751+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-21T10:57:35.980751+00:00'
[2024-07-21T10:57:47.724+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 29, in ingest_data_task
    ingest_data(db_table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 118, in ingest_data
    capture_data_change(pool,table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 89, in capture_data_change
    schema_data_tb = get_schema_avro_file(table_name)
  File "/opt/airflow/plugins/my_modules/ingestion_stage.py", line 34, in get_schema_avro_file
    with open ('table_schema_arvo.json','r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'table_schema_arvo.json'
[2024-07-21T10:57:47.778+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=ingest_data_task, execution_date=20240721T105735, start_date=20240721T105743, end_date=20240721T105747
[2024-07-21T10:57:47.822+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 162 for task ingest_data_task ([Errno 2] No such file or directory: 'table_schema_arvo.json'; 2535)
[2024-07-21T10:57:47.880+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-21T10:57:47.925+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
