[2024-07-22T08:00:36.736+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: fact_order.transform_and_load_task manual__2024-07-22T08:00:29.867606+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
