[2024-07-15T16:04:42.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-15T16:04:37.933130+00:00 [queued]>
[2024-07-15T16:04:42.570+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.ingest_data_task manual__2024-07-15T16:04:37.933130+00:00 [queued]>
[2024-07-15T16:04:42.571+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-15T16:04:42.587+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ingest_data_task> on 2024-07-15 16:04:37.933130+00:00
[2024-07-15T16:04:42.593+0000] {standard_task_runner.py:60} INFO - Started process 213 to run task
[2024-07-15T16:04:42.597+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'ingest_data_task', 'manual__2024-07-15T16:04:37.933130+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmpqpr8wgkr']
[2024-07-15T16:04:42.599+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask ingest_data_task
[2024-07-15T16:04:42.660+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.ingest_data_task manual__2024-07-15T16:04:37.933130+00:00 [running]> on host d3efbe583beb
[2024-07-15T16:04:42.831+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T16:04:37.933130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T16:04:37.933130+00:00'
[2024-07-15T16:04:42.851+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 20, in ingest_data_task
    ingest_data()
  File "/opt/airflow/plugins/modules/ingestion_stage.py", line 117, in ingest_data
    pool = sqlalchemy.create_engine(
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 421, in dbapi
    return __import__("pg8000")
ModuleNotFoundError: No module named 'pg8000'
[2024-07-15T16:04:42.883+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=ingest_data_task, execution_date=20240715T160437, start_date=20240715T160442, end_date=20240715T160442
[2024-07-15T16:04:42.915+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task ingest_data_task (No module named 'pg8000'; 213)
[2024-07-15T16:04:42.930+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-15T16:04:42.960+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
